p_1, p_2 = map(int, input().split())
p_3, p_4 = map(int, input().split())
e_1, e_2, e_3, e_4 = map(int, input().split())
a, b = map(int, input().split())
print(p_1 + 1)
print(p_2 + 1)
print(p_3 + 1)
print(p_4 + 1)
print(e_1 + 1)
print(e_2 + 1)
print(e_3 + 1)
print(e_4 + 1)
print(a + 1)
print(b + 1)
