input_line = input()
array1 = input_line.split(' ')
M = float(array1[0])
P = float(array1[1])
Q = float(array1[2])
ans1 = float(M * P / 100)
ans2 = float(M - ans1)
ans3 = float(ans2 * Q / 100)
ans4 = float(ans2 - ans3)
print(ans4)
